name: Tests

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        version: [stable, nightly]

    name: test_${{ matrix.version }}
    runs-on: ubuntu-latest

    env:
      CI: 1
      CARGO_UNSTABLE_SPARSE_REGISTRY: true

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        run: |
          rustup install ${{ matrix.version }} --no-self-update --profile minimal --force
          rustup override set ${{ matrix.version }}
      - run: cargo generate-lockfile
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2.2.0

      - name: cargo check
        run: cargo check --workspace --bins --examples --tests
        timeout-minutes: 30

      - name: cargo build auditable release
        run: cargo install cargo-auditable && cargo auditable build --release
        timeout-minutes: 30

      - name: cargo audit
        run: cargo audit bin target/release/fs-index
        timeout-minutes: 30

      - name: cargo test
        run: cargo test --workspace --all-features --no-fail-fast
        timeout-minutes: 30

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --all-features --workspace --timeout 120 --fail-under 90 --out Xml
